### PR TITLE
#9 Enable fastlane for testing.

### PR DESCRIPTION
**Pull request by ShengHuaWu**
### Description
Enable `fastlane` and run the tests with `fastlane scan`.

### Note
Travis CI isn't happy because this PR doesn't contain `.travis.yml` file yet.

### CODE REVIEW

**Review by jotshin — APPROVED** [review]
Thanks for this. 👍

**Comment by ShengHuaWu** [comment]
Thanks for your approval.
I'm going to get the green light from Travis CI before merging. 😄

**Comment by ShengHuaWu** [comment]
@jotshin 
I've updated the `.travis.yml` file. 
Please Kindly review. 😄

**Review by jotshin — APPROVED** [review]
Thanks for enabling fastlane. 👍

**Pull request merged**
